name: pmcsms
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  flutter_screenutil: ^5.9.3
  pinput: ^5.0.1
  intl: ^0.20.1
  flutter_load_kit: ^0.0.2
  flutter_secure_storage: ^9.2.2
  loading_animation_widget: ^1.3.0
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.6.1
  smooth_page_indicator: ^1.2.0+3
  equatable: ^2.0.7
  loading_overlay: ^0.4.2
  flutter_animate: ^4.5.2
  webview_flutter: ^4.10.0
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  file_picker: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.11
  very_good_analysis: ^6.0.0



  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/pmcsms_logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
